---
- name: Install nginx
  become: yes
  yum: name=nginx state=present
  tags: nginx

- name: Copy nginx configuration for wordpress
  become: yes
  template: src=default.conf dest=/etc/nginx/conf.d/default.conf
  notify: restart nginx
  tags: nginx
