---
- name: Install Mysql package with yum
  yum: name={{ item }} state=present
  become: yes
  with_items:
   - gcc
   - mysql-devel
   - mysql-server
   - libselinux-python
   - libsemanage-python
  tags: pip

- name: Install Mysql package with pip
  pip: name={{ item }} state=present executable=/usr/local/bin/pip
  become: yes
  with_items:
   - mysql-python
  tags: pip

- name: Configure SELinux to start mysql on any port
  seboolean: name=mysql_connect_any state=true persistent=yes
  become: yes
  when: ansible_selinux.status == "enabled"

- name: Create Mysql configuration file
  template: src=my.cnf.j2 dest=/etc/my.cnf
  become: yes
  notify:
  - restart mysql

- name: Start Mysql Service
  become: yes
  service: name=mysqld state=started enabled=yes
